# 应用服务 WEB 访问端口
server:
  port: 8080

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maritime_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mvc:
    servlet:
      path: /api
  # 上传文件配置
  servlet:
    multipart:
      max-file-size: 5MB #单个文件上传的最大大小
      max-request-size: 20MB # 单次请求上传文件的最大大小，默认10MB

# Mybatis_plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志
    map-underscore-to-camel-case: true # 下划线驼峰命名
  type-aliases-package: com.hs.maritime.bean # 批量别名处理
  # mapper-locations: classpath*:/mapper/*.xml # 加载解析sql映射文件

# 自定义配置：文件上传和下载的路径资源
file:
  # 头像上传路径
  avatar-dir: "E:/JetBrains/IntelliJ IDEA 2024.3.2-workspace/maritime-back/src/main/resources/com/hs/maritime/avatars/"
  # 图书封面上传路径
  cover-dir: "E:/JetBrains/IntelliJ IDEA 2024.3.2-workspace/maritime-back/src/main/resources/com/hs/maritime/covers/"


